// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBrcrE_Qf9dtzvy-N47whR7obTXfQDIE',
    appId: '1:494655940899:web:01b2073d771a35a76d0496',
    messagingSenderId: '494655940899',
    projectId: 'queerloop-c00e6',
    authDomain: 'queerloop-c00e6.firebaseapp.com',
    storageBucket: 'queerloop-c00e6.firebasestorage.app',
    measurementId: 'G-DV7LYX1PN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlQKil0jOWpSejYMEAi0M6GU0TY3RVn4',
    appId: '1:494655940899:android:3d198197f8f43a8f6d0496',
    messagingSenderId: '494655940899',
    projectId: 'queerloop-c00e6',
    storageBucket: 'queerloop-c00e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQhugi3QaA_PLMUabgyrWyUovP11hrjEs',
    appId: '1:494655940899:ios:cc32ae5dac950d786d0496',
    messagingSenderId: '494655940899',
    projectId: 'queerloop-c00e6',
    storageBucket: 'queerloop-c00e6.firebasestorage.app',
    iosBundleId: 'com.queerloop.app',
  );
}
